# node js ?? npm ???
# version ???
FROM node:24-alpine3.21

# make new folder

WORKDIR /app/web

# init project, we have to code
# code
# copy from to
COPY . /app/web

# install lib

RUN npm i
# run app

#PORT 5173:5173

CMD ["npm" ,"run" , "dev"]